# Change these first
owner: glo-markoaular # Your GitHub organization or username, where this repository lives
repo: status-navigate # The name of this repository

sites:
  - name: Navigate
    url: $SITE_1
  - name: Rancher
    url: $SITE_2
  - name: Redmine
    url: $SITE_3

status-website:
  baseUrl: /status-navigate
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Navigate
  introTitle: "**Navigate Services Status**"
  introMessage: "**Welcome to Navigate's Realtime status Page**" 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
